document.write(' <head>\n');
document.write('    <title>AGiDMC</title>\n');
document.write('		<link rel="icon" href="https://agidmc.com/images/logo.jpeg" sizes="32x32" />\n');
document.write('    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">\n');
document.write('    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">\n');
document.write('    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>\n');
document.write('    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">\n');
document.write('    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>\n');
document.write('    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css">\n');
document.write('    <style>html{font-family:Comfortaa;}</style>\n');
/*  document.write( '    <script src="https://agidmc.com/searchbarcountry.js"></script> \n');
document.write( '    <script src="https://agidmc.com/searcbarfunctioncountry.js"></script>\n');
document.write( '    <link rel="stylesheet" type="text/css" href="https://agidmc.com/stylesearchbarcountry.css"> \n'); */
document.write('    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script> \n');
document.writeln("  <script type=\"text/javascript\" src=\"https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit\"></script> ");
document.writeln("         <!-- Global site tag (gtag.js) - Google Analytics --> ");
document.writeln("         <script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-149430200-1\"></script> ");
document.writeln("         <script> ");
document.writeln("         window.dataLayer = window.dataLayer || []; ");
document.writeln("         function gtag(){dataLayer.push(arguments);} ");
document.writeln("         gtag('js', new Date()); ");
document.writeln("  ");
document.writeln("         gtag('config', 'UA-149430200-1'); ");
document.writeln("         </script> ");
document.writeln("  ");
document.write('    <div class="navbar-fixed navbar" id="navbar">\n');
document.write('      <nav>\n');
document.write('        <ul id="language" class="dropdown-content language">\n');
document.write('            <li><a class="black-text triggers hoverable">ENGLISH</a></li>\n');
document.write('            <li><a class="black-text triggers hoverable" > 简体中文</a></li>\n');
document.write('            <li><a class="black-text triggers hoverable"> 繁體中文</a></li>\n');
document.write('            <li><a class="black-text triggers hoverable"> BAHASA INDONESIA</a></li>\n');
document.write('            <li><a class="black-text triggers hoverable"> 日本語</a></li>\n');
document.write('            <li><a class="black-text triggers hoverable"> 한국어</a></li>\n');
document.write('            <li><a class="black-text triggers hoverable"> ภาษาไทย</a></li>\n');
document.write('            <li><a class="black-text triggers hoverable"> TIẾNG VIỆT</a></li>\n');
document.write('            <li><a class="black-text triggers hoverable"> हिन्दी</a></li>\n');
document.write('            <li><a class="black-text triggers hoverable"> বাংলা</a></li>\n');
document.write('            <li><a class="black-text triggers hoverable"> தமிழ்</a></li>\n');
document.write('        </ul>\n');
document.write('        <ul id="currency" class="dropdown-content currency">\n');
document.write('            <div class="row">\n');
document.write('                <div class="col s3 m3">\n');
document.write('                    <li><a class="black-text currency ">JPY</a></li>\n');
document.write('                    <li><a class="black-text currency ">SGD</a></li>\n');
document.write('                    <li><a class="black-text currency ">EUR</a></li>\n');
document.write('                    <li><a class="black-text currency ">USD</a></li>\n');
document.write('                </div>\n');
document.write('                <div class="col s3 m3">\n');
document.write('                    <li><a class="black-text currency ">INR</a></li>\n');
document.write('                    <li><a class="black-text currency ">AED</a></li>\n');
document.write('                    <li><a class="black-text currency ">PHP</a></li>\n');
document.write('                    <li><a class="black-text currency ">CNY</a></li>\n');
document.write('                </div>\n');
document.write('                <div class="col s3 m3">\n');
document.write('                    <li><a class="black-text currency ">THB</a></li>\n');
document.write('                    <li><a class="black-text currency ">HKD</a></li>\n');
document.write('                    <li><a class="black-text currency ">GBP</a></li>\n');
document.write('                </div>\n');
document.write('                <div class="col s3 m3">\n');
document.write('                    <li><a class="black-text currency ">AUD</a></li>\n');
document.write('                    <li><a class="black-text currency ">IDR</a></li>\n');
document.write('                    <li><a class="black-text currency ">CAD</a></li>\n');
document.write('                </div>\n');
document.write('            </div> \n');
document.write('        </ul>\n');
document.write('        <ul id="profile" class="dropdown-content profile">\n');
document.write('            <li><a href="/profile" class="black-text triggers hoverable">My Account</a></li>\n');
document.write('            <li><a href="/subuser" class="black-text triggers hoverable">Sub User</a></li>\n');
document.write('            <li><a href="/subagent" class="black-text triggers hoverable">Sub Agent</a></li>\n');
document.write('            <li><a href="/company" class="black-text triggers hoverable">Company</a></li>\n');
document.write('        </ul>\n');
document.write('        <ul id="navBalance" class="dropdown-content profile">\n');
document.write('            <li><a href="/bookings" class="black-text triggers hoverable">My Bookings</a></li>\n');
document.write('            <li><a href="/balance" class="black-text triggers hoverable">Top Up</a></li>\n');
document.write('        </ul>\n');
document.write('          <ul id="notification" class="dropdown-content black-text notifications notification">\n');
document.write('           <div class="row">\n');
document.write('             <div id="free" class="col s12 m7">\n');
document.write('               <div  onclick="TypeNotification()" style="font-size: larger;font-weight: bold;letter-spacing: 1px;">Notification</div>\n');
document.write('             </div>\n');
document.write('             <div  id="off" class="col s12 m5">\n');
document.write('              <div  onclick="OfferNotification()" style="font-size: larger;font-weight: bold;letter-spacing: 1px;">Offer</div>\n');
document.write('            </div>\n');
document.write('           </div>\n');
document.write('            <div class="row">\n');
document.write('                <div class="col s12 m12">\n');
document.write('                    <li id="show"></li>\n');
document.write('                </div>\n');
document.write('            </div>\n');
document.write('            <div class="row">\n');
document.write('                <div class="col s12 m12">\n');
document.write('                    <li id="show2"></li>\n');
document.write('                </div>\n');
document.write('            </div>\n');
document.write('          \n');
document.write('        </ul>');
document.write('        <div>\n');
document.write('          <div class="nav-wrapper">\n');
document.write('            <ul class="hide-on-med-and-down Navbar">\n');
document.write('              <li><i class="material-icons large notranslate"  onclick="hidesidebar()" style=" cursor: pointer;margin-left:20px">menu</i></li>\n');
document.write('            <li><a class="" href="/"><img  class="logo img" id="logohideside"  src="https://agidmc.com/images/logo.svg"></a>\n');
document.write('           \n');
document.write('            </ul>\n');
document.write('           \n');
document.write('           <a href="/" class="center-align"><img  class="center-align img" id="mobilelogo" src="https://agidmc.com/images/logo.svg"></a>\n');
document.write('            <a href="/" data-target="mobile-demo" class="top-nav sidenav-trigger"><i class="notranslate tiny material-icons" style="margin-top:-65px;" id="">menu</i></a>\n');
document.write('            \n');
document.write('            <ul class="right hide-on-med-and-down Navbar" id="nav-mobile" style="position:fixed;right:0 !important;">\n');
document.write('              \n');
/*  document.write( '               <li>\n');
document.write( '                   <div class="">\n');
document.write( '                  <form>\n');
document.write( '               <div class="input-field search" style="height:65px;">\n');
document.write( '               <input id="searchnav" class="modal-trigger" type="search"  data-target="search-popupcountry" onclick="searchedpopup()" required style="background-color:white;">\n');  
document.write( '                    <label class="label-icon" for="search"><i class="material-icons black-text">search</i></label>\n');
document.write( '               <i class="material-icons  black-text">close</i>\n');
document.write( '                   </div>\n');
document.write( '               </form>\n');
document.write( '                   </div>\n');
document.write( '                 </li>\n'); */
document.write('                <li style="">\n');
document.write('                    <a class="sidenav-close modal-trigger" href="#modal1"><b class=" white-text">AGi Academy</b><i class="white-text notranslate left small fa fa-university" style="margin-right:5px;" aria-hidden="true"></i></a>\n');
document.write('                </li>\n');
document.write('                 <li class="notification sidenav-close"><div  id="google_translate_element"></div></li>\n');
document.write('                <li style="">\n');
document.write('                    <a class="dropdown-trigger white-text notification sidenav-close"  data-target="currency"><b id="selectedCurrency" class=" white-text">Currency</b></a>\n');
document.write('                </li>');
document.write('                <li>');
document.write('                    <a class="white-text dropdown-trigger sidenav-close notification"  data-target="navBalance"><b class=" white-text">Balance:<span id="balanceDisplay" ></span></b></a>');
document.write('                </li>');
document.write('                <li>');
document.write('                    <a class="white-text dropdown-trigger sidenav-close notification"  data-target="profile"><b class=" white-text">Profile</b></a>');
document.write('                </li>');
document.write('                <li>');
document.write('                 <a class="sidenav-close  dropdown-trigger  notification" id="notificationdropdown" data-target="notification"><i class="white-text notranslate notiny bubble material-icons">notifications</i></a>');
document.write('                </li>');
document.write('                <li>');
document.write('                 <a class="sidenav-close notification" href="/cart"><i class="white-text notranslate bubble material-icons">add_shopping_cart</i></a>');
document.write('                </li>');
document.write('                <li>');
document.write('                    <a onclick="signout()" class="white-text  sidenav-close " href="/signout"><b class=" white-text">SignOut</b></a>');
document.write('                </li>');
document.write('            </ul>\n');
document.write('            </div>\n');
document.write('        </div>\n');
document.write('      </nav>\n');
document.write('    </div>\n');
document.write('  </head>\n');
document.write('      <ul class="sidenav scrollspy" id="mobile-demo">\n');
document.write('       \n');
document.write('       \n');
document.write('          \n');
document.write('        <li class="center" ><img class="center white-text notranslate " style="margin-top:15px;border-radius: 50%;" src="/myImage" alt="Logo"  height="100px" width="100px" /></li>\n');
document.write('      <li><p class="center-align white-text userName" id="userName">Agent</p></li> \n');
document.write('      <li><p class="center-align white-text companyName" id="companyName">AGi DMC</p> </li> \n');
document.write('        <li><a class=" modal-trigger hoverable sidebardata sidenav-close" href="/" style="margin-top:-25px "><i class="material-icons sidetext tiny notranslate" >dashboard</i><p class="text">DASHBOARD</p></a></li>\n');
document.write('        <li><a  class=" modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext tiny" >location_city</i><p class="text">INSURANCE</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1" ><i  class="material-icons notranslate sidetext  tiny" >money</i><p class="text" >VISA SERVICES</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">dashboard</i><p class="text" >FOREX / REMITTANCE</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/flights"><i class="material-icons notranslate sidetext  tiny">flight_takeoff</i><p class="text" >FLIGHTS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">hotel</i><p class="text" >HOTELS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/transfers"><i class="material-icons notranslate sidetext  tiny">local_atm</i><p class="text" >TRANSFERS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/"><i class="material-icons notranslate sidetext  tiny">photo_library</i><p class="text" >ATTRACTIONS / DAYTOURS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/food"><i class="material-icons notranslate sidetext  tiny">local_dining</i><p class="text" >FOOD/BUFFET VOUCHERS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/wifisim"><i class="material-icons notranslate sidetext  tiny">network_wifi</i><p class="text">WIFI / E SIMS / SIM CARD</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">shopping_basket</i><p class="text" >TRAVEL ESSENTIAL</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext tiny">store</i><p class="text" >RENTALS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">business_center</i><p class="text">READY PACKAGES</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">local_taxi</i><p class="text" >TRIP PLANNER</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">money</i><p class="text">GET LOAN</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/bookings"><i class="material-icons notranslate sidetext  tiny">shopping_cart</i><p class="text" >MY BOOKINGS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/reports"><i class="material-icons notranslate sidetext  tiny">shopping_basket</i><p class="text" >REPORTS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/balance"><i class="material-icons notranslate sidetext  tiny">assessment</i><p class="text" >TOPUP</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">group</i><p class="text">CUSTOMERMANAGEMENT</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">business_center</i><p class="text" >MARKETING</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">account_circle</i><p class="text" >REFERALS / LOYALITY</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">account_circle</i><p class="text" >AGI ACADEMY</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">chat</i><p class="text" >CUSTOMER SUPPORT</p></a></li>\n');
document.write('       \n');
document.write('         <li><div id="google_translate_element"></div></li>\n');
document.write('            <li>\n');
document.write('                <a class="dropdown-trigger" id="money" data-target="currency1"><i class="notranslate material-icons sidetext tiny">account_balance_wallet</i><p class="text">CURRENCY</p></a>\n');
document.write('                  <ul id="currency1" class="dropdown-content currency">\n');
document.write('                    <div class="row">\n');
document.write('                      <div class="col s3 m3">\n');
document.write('                        <li><a class="black-text currency  sidenav-close">JPY</a></li>\n');
document.write('                        <li><a class="black-text currency  sidenav-close">SGD</a></li>\n');
document.write('                        <li><a class="black-text currency  sidenav-close">EUR</a></li>\n');
document.write('                        <li><a class="black-text currency  sidenav-close ">USD</a></li>\n');
document.write('                      </div>\n');
document.write('                      <div class="col s3 m3">\n');
document.write('                        <li><a class="black-text currency  sidenav-close">INR</a></li>\n');
document.write('                        <li><a class="black-text currency  sidenav-close">AED</a></li>\n');
document.write('                        <li><a class="black-text currency  sidenav-close">PHP</a></li>\n');
document.write('                        <li><a class="black-text currency  sidenav-close">CNY</a></li>\n');
document.write('                      </div>\n');
document.write('                      <div class="col s3 m3">\n');
document.write('                        <li><a class="black-text currency  sidenav-close">THB</a></li>\n');
document.write('                        <li><a class="black-text currency  sidenav-close">HKD</a></li>\n');
document.write('                        <li><a class="black-text currency  sidenav-close">GBP</a></li>\n');
document.write('                      </div>\n');
document.write('                      <div class="col s3 m3">\n');
document.write('                        <li><a class="black-text currency  sidenav-close">AUD</a></li>\n');
document.write('                        <li><a class="black-text currency sidenav-close ">IDR</a></li>\n');
document.write('                        <li><a class="black-text currency sidenav-close ">CAD</a></li>\n');
document.write('                      </div>\n');
document.write('                    </div> \n');
document.write('                  </ul>\n');
document.write('            </li>\n');
document.write('           \n');
document.write('            \n');
document.write('            <li>\n');
document.write('                <a class="dropdown-trigger" href="" id="myprofile" data-target="profile1"><i class="material-icons sidetext notranslate tiny">account_circle</i><p class="text">PROFILE</p></a class="sidenav-close">\n');
document.write('                  <ul id="profile1" class="dropdown-content profile">\n');
document.write('                    <li><a href="/profile" class="black-text triggers sidenav-close hoverable">My Account</a></li>\n');
document.write('                    <li><a href="/subuser" class="black-text triggers sidenav-close hoverable">Sub User</a></li>\n');
document.write('                    <li><a href="/subagent" class="black-text triggers sidenav-close hoverable">Sub Agent</a></li>\n');
document.write('                       <li><a href="/company" class="black-text triggers sidenav-close hoverable">Company</a></li>\n');
document.write('                </ul>\n');
document.write('            </li>\n');
document.write('            <li>\n');
document.write('                <a class="dropdown-trigger" id="mybalance" data-target="balance1"><i class="white-text material-icons sidetext notranslate tiny">account_balance_wallet</i><p class="text">MYBALANCE</p></a class="sidenav-close">\n');
document.write('            </li>\n');
document.write('                  <ul id="balance1" class="dropdown-content balance">\n');
document.write('                    <li><a href="" class="black-text triggers sidenav-close hoverable">My Bookings</a></li>\n');
document.write('                    <li><a href="" class="black-text triggers sidenav-close hoverable">Top Up</a></li>\n');
document.write('                </ul>\n');

document.write('            <li> <a class="dropdown-trigger" id="followus" data-target="follow"><i class="material-icons sidetext notranslate tiny">account_circle</i><p class="text">FOLLOW US</p></a></li>\n');
document.write('            <ul id="follow" class="dropdown-content">\n');
document.write('                <span><a href="https://www.facebook.com/AGiDMC/"  target="_blank"><i class="small fab fa-facebook notranslate agi-social sidenav-close" style="color: #3b5998;" ></i></a> \n');
document.write('                    <a href-="https://twitter.com/agi_dmc"  target="_blank"><i class="small fab fa-twitter notranslate agi-social sidenav-close" style="color: #00acee;"></i></a> \n');
document.write('                    <a href="https://www.instagram.com/agidmc/"  target="_blank"><i class="small fab fa-instagram notranslate agi-social sidenav-close" style="color: #3f729b;"></i></a>\n');
document.write('                    <a  href="https://www.pinterest.com/AGiDMC/"  target="_blank"> <i class="small fab fa-pinterest notranslate  agi-social sidenav-close" style="color: #c8232c;"></i> </a> \n');
document.write('                    <a href="https://linkedin.com/company/agidmc"  target="_blank"> <i class="small fab fa-linkedin notranslate agi-social sidenav-close" style="color: #0e76a8;"></i></a> \n');
document.write('                    <a href="https://wa.me/6596531921s"  target="_blank"><i class="small fab fa-whatsapp agi-social notranslate sidenav-close" style="color: #4fce5d;"></i></a>\n');
document.write('                    <a href="https://www.youtube.com/channel/UCDaRE5WFvp6KBrGNYXVs6jg?view_as=public" target="_blank">\n');
document.write('                    <i class="small fab fa-youtube agi-social notranslate  sidenav-close" style="color: #c4302b;"></i></a>\n');
document.write('                    <a href="https://www.blogger.com/about/?r=2" target="_blank"><i class="small fas fa-blog agi-social notranslate sidenav-close" style="color:#ff5722"></i></a>\n');
document.write('                </span>\n');
document.write('            </ul>\n');
document.write('                <li>');
document.write('                 <a class=""  href="/cart"><i class="white-text notranslate sidetext bubble material-icons tiny">add_shopping_cart</i><p class="text sidenav-close">CART</p></a>');
document.write('                </li>');
document.write('            <li>\n');
document.write('              <a onclick="signout()" class="" href="/signout"><i class="white-text material-icons sidetext notranslate tiny">exit_to_app</i><p class="text sidenav-close">SIGNOUT</p></a>\n');
document.write('            </li>\n');
document.write('        </ul>\n');
document.write('        \n');
document.write('          \n');
document.write('      </ul>\n');
document.write('    \n');
document.write('        \n');
document.write('       \n');
document.write('      \n');
document.write('      <ul id="slide-out" class="sidenav">\n');
document.write('        \n');
document.write('        <li class="center" ><img class="center white-text notranslate " style="margin-top:15px;border-radius:50%;" src="/myImage" alt="Logo" height="100px" width="100px" /></li>\n');
document.write('      <li><p class="center-align white-text userName1" id="userName1">Agent</p></li> \n');
document.write('      <li><p class="center-align white-text companyName1" id="companyName1">AGi DMC</p> </li> \n');
document.write('        <li><a class=" modal-trigger hoverable sidebardata sidenav-close" href="/" style="margin-top:-25px "><i class="material-icons notranslate sidetext tiny" >dashboard</i><p class="text" id="dashboard">DASHBOARD</p></a></li>\n');
document.write('        <li><a  class=" modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext tiny" >location_city</i><p class="text">INSURANCE</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1" ><i  class="material-icons notranslate sidetext  tiny" >money</i><p class="text" >VISA SERVICES</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">dashboard</i><p class="text" >FOREX / REMITTANCE</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/flights"><i class="material-icons notranslate sidetext  tiny">flight_takeoff</i><p class="text" >FLIGHTS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">hotel</i><p class="text">HOTELS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/transfers"><i class="material-icons notranslate sidetext  tiny">local_atm</i><p class="text">TRANSFERS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/"><i class="material-icons notranslate sidetext  tiny">photo_library</i><p class="text">ATTRACTION / DAY TOURS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/food"><i class="material-icons notranslate sidetext  tiny">local_dining</i><p class="text">FOOD/BUFFET VOUCHERS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="/wifisim"><i class="material-icons notranslate sidetext  tiny">network_wifi</i><p class="text">WIFI / E-SIM / SIM CARD</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">shopping_basket</i><p class="text">TRAVEL ESSENTIAL</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">store</i><p class="text" >RENTALS</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">business_center</i><p class="text">READY PACKAGES</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">local_taxi</i><p class="text">TRIP PLANNER</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">money</i><p class="text">GET LOAN</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">group</i><p class="text">CRM</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">business_center</i><p class="text">MARKETING</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">account_circle</i><p class="text">REFERALS / LOYALITY</p></a></li>\n');
document.write('        <li><a class="modal-trigger hoverable sidebardata sidenav-close" href="#modal1"><i class="material-icons notranslate sidetext  tiny">chat</i><p class="text">CUSTOMER SUPPORT</p></a></li>\n');

document.write('      </ul>\n');
document.write('\n');
document.write('\n');
document.write('  <!-- Modal Structure -->\n');
document.write('<div id="modal1" class="modal-action modal m2 l4 modal-close comingSoon">\n');
document.write('  <div>\n');
document.write('  <img alt="AGi DMC" src="https://agidmc.com/images/19.gif" height="300px" width="100%">\n');
document.write('  </div>\n');
document.write('  \n');
document.write('  </div>');
document.write('\n');



document.write('        <div  id="loader" class="center preloader-wrapper loading big active">\n');
document.write('            <div class="spinner-layer spinner-blue">\n');
document.write('              <div class="circle-clipper left">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div><div class="gap-patch">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div><div class="circle-clipper right">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div>\n');
document.write('            </div>\n');
document.write('      \n');
document.write('            <div class="spinner-layer spinner-red">\n');
document.write('              <div class="circle-clipper left">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div><div class="gap-patch">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div><div class="circle-clipper right">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div>\n');
document.write('            </div>\n');
document.write('      \n');
document.write('            <div class="spinner-layer spinner-yellow">\n');
document.write('              <div class="circle-clipper left">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div><div class="gap-patch">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div><div class="circle-clipper right">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div>\n');
document.write('            </div>\n');
document.write('      \n');
document.write('            <div class="spinner-layer spinner-green">\n');
document.write('              <div class="circle-clipper left">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div><div class="gap-patch">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div><div class="circle-clipper right">\n');
document.write('                <div class="circle"></div>\n');
document.write('              </div>\n');
document.write('            </div>\n');
document.write('        </div>');




document.addEventListener('DOMContentLoaded', function () {
    var elems = document.querySelectorAll('.dropdown-trigger');
    var instances = M.Dropdown.init(elems, { coverTrigger: false });
    var elems = document.querySelectorAll('.modal');
    var instances = M.Modal.init(elems, {});
    setTimeout(() => {
        var elem = document.getElementById('notification');
        M.Dropdown.init(elem, { coverTrigger: false, closeOnClick: false });
    }, 1000);
});


function googleTranslateElementInit() {
    new google.translate.TranslateElement({
        pageLanguage: 'en', includedLanguages: 'en,ru,zh-CN,id,ja,ko,th,hi,BN,ta,ms,en-PH',
        layout: google.translate.TranslateElement.InlineLayout.SIMPLE
    }, 'google_translate_element');
}

if (window.top !== window.self) { window.top.location = window.self.location; }
